import Head from "next/head";
import Image from "next/image";
import { PrimaryLink } from "~/components/PrimaryLink";

function HeroBanner() {
  return (
    <section className="grid grid-cols-2">
      <div>
        <h1 className="text-6xl">Generate Corporate Memphis art!</h1>
        <p>Use AI to generate assets in seconds!</p>
        <PrimaryLink href="/generate"> Generate </PrimaryLink>
      </div>
      <Image
        src="/banner-temp.jpg"
        alt="an image of example corporate memphis art"
        width="500"
        height="500"
      />
    </section>
  );
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Corporate Memphis AI</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <HeroBanner />
      </main>
    </>
  );
}
